# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py{311,313,314}-{linux,windows,macos}-pyqt6, py313-{linux,windows}-pyside6, py313-{linux,windows}-pyqt5

[gh-actions]
python =
    3.11: py311
    3.13: py313
    3.14: py314

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

QT_PACKAGE =
    pyqt6: pyqt6
    pyside6: pyside6
    pyqt5: pyqt5
    pyside2: pyside2

[testenv]
platform =
    linux: linux
    macos: darwin
    windows: win32
passenv =
    CI
    GITHUB_ACTIONS
    DISPLAY
    XAUTHORITY
    NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
    PYVISTA_OFF_SCREEN
    QT_PACKAGE
dependency_groups =
    dev

commands = pytest -v --color=yes --cov=napari_animation --cov-report=xml

[testenv:py{311,313,314}-{linux,macos,windows}-pyqt6]
deps =
    napari[pyqt6]

[testenv:py313-{linux,windows}-pyside6]
deps =
    napari[pyside6]

[testenv:py313-{linux,windows}-pyqt5]
deps =
    napari[pyqt5]
