# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py{310,311,312,313,314}-{linux,macos,windows}-pyqt6, py312-{linux,windows}-pyside6, py312-{linux,windows}-pyqt5, py312-{linux,macos}-pyside2

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

QT_PACKAGE =
    pyqt6: pyqt6
    pyside6: pyside6
    pyqt5: pyqt5
    pyside2: pyside2

[testenv]
platform =
    linux: linux
    macos: darwin
    windows: win32
passenv =
    CI
    GITHUB_ACTIONS
    DISPLAY
    XAUTHORITY
    NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
    PYVISTA_OFF_SCREEN
    QT_PACKAGE

deps =
    pytest  # https://docs.pytest.org/en/latest/contents.html
    pytest-cov  # https://pytest-cov.readthedocs.io/en/latest/
    pytest-qt  # https://pytest-qt.readthedocs.io/en/latest/intro.html
    pytest-xvfb ; sys_platform == 'linux'
commands = pytest -v --color=yes --cov=napari_animation --cov-report=xml

[testenv:py{310,311,312,313,314}-{linux,macos,windows}-pyqt6]
deps =
    {[testenv]deps}
    napari[pyqt6]

[testenv:py312-{linux,windows}-pyside6]
deps =
    {[testenv]deps}
    napari[pyside6]

[testenv:py312-{linux,windows}-pyqt5]
deps =
    {[testenv]deps}
    napari[pyqt5]

[testenv:py312-{linux,macos}-pyside2]
deps =
    pytest-qt<4.5
    {[testenv]deps}
    napari[pyside2]<0.7.0
